# A service is an abstraction for pods, providing a stable, virtual IP (VIP) address.
kind: Service
apiVersion: v1
metadata:
  name: rpi-lnp-nginx-deploy
  namespace: rpi-lnp
spec:
  # nodePort is the port that a client outside of the cluster will "see".
  # nodePort is opened on every node in your cluster.
  type: NodePort
  ports:
    - port: 80
      nodePort: 30081
      name: http
    - port: 443
      nodePort: 30444
      name: https
  # assign cluster ip manually, The IP address that a user chooses must be a valid IP address
  # and within the service-cluster-ip-range
  clusterIP: 10.96.100.88
  # just like the selector in the deployment,
  # but this time it identifies the set of pods to load balance
  # traffic to.
  selector:
    app: rpi-lnp-nginx
---
kind: Service
apiVersion: v1
metadata:
  name: rpi-lnp-php71-deploy
  namespace: rpi-lnp
spec:
  type: NodePort
  ports:
    - port: 9000
      nodePort: 30070
      name: php71
  clusterIP: 10.96.100.77
  selector:
    app: rpi-lnp-php71
# ---
# kind: Service
# apiVersion: v1
# metadata:
#   name: shkpgh-mysql57-deploy
# spec:
#   type: NodePort
#   ports:
#     - port: 3306
#       nodePort: 30136
#       name: php71
#   clusterIP: 10.96.100.136
#   selector:
#     app: shkpgh-mysql57
